# Generated by Django 3.0 on 2019-12-16 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_auto_20191211_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
