# Generated by Django 3.0 on 2019-12-16 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_tracker.Board'),
            preserve_default=False,
        ),
    ]
