# Generated by Django 3.0 on 2019-12-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0006_epic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_tracker.Epic'),
        ),
    ]
