# Generated by Django 3.0 on 2019-12-20 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0007_task_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
